### ISSUE TITLE
MemCacheTicketRegistryTests fail

### ISSUE THREAD

**Issue by mongolu** [Jasig/cas#1004]
When compiling cas-master (cas-4.1.0-SNAPSHOT), it stops at "Apereo CAS Memcached Integration".

This is in file `/cas-server-integration-memcached/target/surefire-reports/TEST-org.jasig.cas.ticket.registry.MemCacheTicketRegistryTests.xml`

  <testcase name="org.jasig.cas.ticket.registry.MemCacheTicketRegistryTests" classname="org.jasig.cas.ticket.registry.MemCacheTicketRegistryTests" time="0.435">
    <error message="Could not start process:can&apos;t run as root without the -u switch&#10;" type="java.io.IOException"><![CDATA[java.io.IOException: Could not start process:can't run as root without the -u switch

	at de.flapdoodle.embed.memcached.MemcachedProcess.onAfterProcessStart(MemcachedProcess.java:140)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:112)
	at de.flapdoodle.embed.memcached.MemcachedProcess.<init>(MemcachedProcess.java:60)
	at de.flapdoodle.embed.memcached.MemcachedExecutable.start(MemcachedExecutable.java:53)
	at de.flapdoodle.embed.memcached.MemcachedExecutable.start(MemcachedExecutable.java:35)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
	at org.jasig.cas.ticket.registry.MemCacheTicketRegistryTests.beforeClass(MemCacheTicketRegistryTests.java:90)
]]></error>
    <system-out><![CDATA[Extract /root/.embedmemcache/1.4.22_1/memcached-dist-1.4.22_1-linux.tar.gz START
[memcached error]can't run as root without the -u switch
[memcached error] 2015-06-24 00:15:00,986 ERROR [de.flapdoodle.embed.process.runtime.AbstractProcess] - <failed to call [onAfterProcessStart(), java.io.IOException: Could not start process:can't run as root without the -u switch
]>
2015-06-24 00:15:00,986 ERROR [de.flapdoodle.embed.process.runtime.AbstractProcess] - <failed to call [onAfterProcessStart(), java.io.IOException: Could not start process:can't run as root without the -u switch
]>
]]></system-out>
    <system-err><![CDATA[Jun 24, 2015 12:15:00 AM de.flapdoodle.embed.memcached.MemcachedProcess stopInternal
INFO: try to stop memcached
Jun 24, 2015 12:15:00 AM de.flapdoodle.embed.memcached.MemcachedProcess stopInternal
WARNING: could not kill memcached, try next
Jun 24, 2015 12:15:01 AM de.flapdoodle.embed.memcached.MemcachedProcess stopInternal
WARNING: could not term memcached, try next
Jun 24, 2015 12:15:01 AM de.flapdoodle.embed.memcached.MemcachedProcess stopInternal
WARNING: could not stop memcached the third time, try one last thing
]]></system-err>
  </testcase>

I am running on a `Centos 6.5` with `java-1.7.0-openjdk-1.7.0.79-2.5.5.1.el7_1.x86_64`.

**Comment by mongolu** [comment]
I've done `su` to a user (which is in `wheel` group) and it passed this test.
