### ISSUE TITLE
sign logout make errors sometimes 

### ISSUE THREAD

**Issue by icanfly** [Jasig/cas#1007]
I'm using sign logout in some apps ( include proxy mode). 

When I did the logout action  I will get some errors sometimes

and it make some application keep it's session still (logout failed).

but sometimes it's ok. (worked good).

I can't find out what this happened. Is it a bug ?

I'm using trunk branch. 

when error happened, I get some errors like below:

CAS Client ERROR:

ERROR CommonUtils:420- Server returned HTTP response code: 500 for URL: http://sso.xxx-inc.com:6809/proxyValidate?pgtUrl=http%3A%2F%2Fapp1.xxx-inc.com%2FproxyCallback&ticket=ST-293-5UytuoIc55Y6XeozW7zf-cas01.example.org&service=http%3A%2F%2Fapp1.xxx-inc.com%2Fadmin%2FmemberList
java.io.IOException: Server returned HTTP response code: 500 for URL: http://sso.xxx-inc.com:6809/proxyValidate?pgtUrl=http%3A%2F%2Fapp1.xxx-inc.com%2FproxyCallback&ticket=ST-293-5UytuoIc55Y6XeozW7zf-cas01.example.org&service=http%3A%2F%2Fapp1.xxx-inc.com%2Fadmin%2FmemberList

CAS Server ERROR:

2015-06-26 14:03:40,291 DEBUG [org.jasig.cas.web.FlowExecutionExceptionResolver] - <Ignoring the received exception due to a type mismatch>
java.lang.IllegalStateException: TicketGrantingTicket already generated for this ServiceTicket.  Cannot grant more than one TGT for ServiceTicket
        at org.jasig.cas.ticket.ServiceTicketImpl.grantTicketGrantingTicket_aroundBody8(ServiceTicketImpl.java:143) ~[cas-server-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
        at org.jasig.cas.ticket.ServiceTicketImpl$AjcClosure9.run(ServiceTicketImpl.java:1) ~[cas-server-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.5.jar:?]
        at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44) ~[inspektr-aspects-1.2.GA.jar:1.2.GA]
        at org.jasig.cas.ticket.ServiceTicketImpl.grantTicketGrantingTicket(ServiceTicketImpl.java:141) ~[cas-server-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
        at org.jasig.cas.CentralAuthenticationServiceImpl.delegateTicketGrantingTicket_aroundBody6(CentralAuthenticationServiceImpl.java:412) ~[cas-server-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
        at org.jasig.cas.CentralAuthenticationServiceImpl$AjcClosure7.run(CentralAuthenticationServiceImpl.java:1) ~[cas-server-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.5.jar:?]
        at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44) ~[inspektr-aspects-1.2.GA.jar:1.2.GA]
        at org.jasig.cas.CentralAuthenticationServiceImpl.delegateTicketGrantingTicket(CentralAuthenticationServiceImpl.java:391) ~[cas-server-core-4.1.0-SNAPSHOT.jar:4.1.0-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.jasig.inspektr.audit.AuditTrailManagementAspect.handleAuditTrail(AuditTrailManagementAspect.java:128) ~[inspektr-audit-1.2.GA.jar:1.2.GA]
        at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.6.RELEASE.jar:4.1.6.RELEASE]

Caused by:
java.lang.IllegalStateException: TicketGrantingTicket already generated for this ServiceTicket.  Cannot grant more than one TGT for ServiceTicket
        at org.jasig.cas.ticket.ServiceTicketImpl.grantTicketGrantingTicket_aroundBody8(ServiceTicketImpl.java:143)
        at org.jasig.cas.ticket.ServiceTicketImpl$AjcClosure9.run(ServiceTicketImpl.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
        at org.jasig.cas.ticket.ServiceTicketImpl.grantTicketGrantingTicket(ServiceTicketImpl.java:141)
        at org.jasig.cas.CentralAuthenticationServiceImpl.delegateTicketGrantingTicket_aroundBody6(CentralAuthenticationServiceImpl.java:412)
        at org.jasig.cas.CentralAuthenticationServiceImpl$AjcClosure7.run(CentralAuthenticationServiceImpl.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
        at org.jasig.cas.CentralAuthenticationServiceImpl.delegateTicketGrantingTicket(CentralAuthenticationServiceImpl.java:391)
        at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
        at org.jasig.inspektr.audit.AuditTrailManagementAspect.handleAuditTrail(AuditTrailManagementAspect.java:128)
        at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at com.ryantenney.metrics.spring.MeteredMethodInterceptor.invoke(MeteredMethodInterceptor.java:45)
        at com.ryantenney.metrics.spring.MeteredMethodInterceptor.invoke(MeteredMethodInterceptor.java:32)

**Comment by icanfly** [comment]
I didn't do anything , but It happened you passed by

**Comment by mmoayyed** [comment]
Based on your logs, it appears that you are using trying to use an ST multiple times to generate proxy granting tickets. This is a legitimate error. You should look into why the app tries to do this first.
