### ISSUE TITLE
OpenId 2.0 "openid.ns" parameter missing

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1058]
I was trying to configure OpenID Provider with jasig cas server 3.5.2.  I am using a custom client developed using openid4java library.   I tried both smart and dumb mode and both authentication and signature   verifications worked for me.   But what I found was in dumb mode, in response to the   openid.mode=check_authentication, the cas server responded with only   below two parameters:  openid.mode-id_res  is_valid=true   However in the openid specification it says that, in cass of openid   2.0 the parameter openid.ns is also mandatory. But in openid 1.0 the   parameter is optional.   So that means my Jasig Cas is running openid 1.0 provider.   How to configure it to use OpenId 2.0 Provider?

**Comment by leleuj** [comment]
The `openid4java` library supports OpenID 2.0, though I'm not sure how to configure that.

**Comment by mmoayyed** [comment]
Think it may be a CAS issue, that it's not actually returning the right response. Could you perhaps set up a dev environment and walk through it? It seems to me that if the parameter is optional in v1 and required in v2, we might as well pass it along where needed.

**Comment by mmoayyed** [comment]
I did mark this for 4.0.4, but if we determine that it cannot meet the release timeline, might have to push back to 4.0.5

**Comment by mmoayyed** [comment]
@leleuj do you think this might be something you can tackle?

**Comment by leleuj** [comment]
Yes, I'll try to find out what's going on, this week or next one.

**Comment by leleuj** [comment]
I think it depends on the way to declare your CAS server as an OpenID provider: check https://github.com/leleuj/cas-openid-demo/commit/ddcc62c2dc61f76bd513c1ee62b73e5a0c88f318 : I'm not absolutely sure, but I think it turns my CAS server as an OpenID provider **version 2.0**.

**Comment by mmoayyed** [comment]
OK, let me ask. In your demo, does the server return back a "openid.ns" parameter back to the client? And is that because you configured in a specific way? In which case, what are the set of steps followed? Can we document them?

**Comment by mmoayyed** [comment]
I tried the demo, but failed. I see:

```bash
OPENID CLIENT DEMO 2015/08/02 23:04:39,757 DEBUG [qtp24058238-28] org.openid4java.message.ParameterList - Creating parameter list from key-value form:

openid.mode:id_res
is_valid:true

OPENID CLIENT DEMO 2015/08/02 23:04:39,765 DEBUG [qtp24058238-28] org.openid4java.message.ParameterList - Created empty parameter list.
OPENID CLIENT DEMO 2015/08/02 23:04:39,766 ERROR [qtp24058238-28] org.leleuj.MainController - message exception
org.openid4java.message.MessageException: 0x100: Invalid Key-Value form, colon missing:
        at org.openid4java.message.ParameterList.createFromKeyValueForm(ParameterList.java:199)
        at org.openid4java.consumer.ConsumerManager.call(ConsumerManager.java:620)
        at org.openid4java.consumer.ConsumerManager.verifySignature(ConsumerManager.java:1808)
        at org.openid4java.consumer.ConsumerManager.verify(ConsumerManager.java:1179)
        at org.leleuj.MainController.openId(MainController.java:99)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:213)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:126)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:96)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:617)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:578)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:648)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:559)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:365)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
```

**Comment by mmoayyed** [comment]
I ran through the sequence once more. It turns out that openid.ns is returned from CAS just fine. But, signature verification fails because the successful authentication response cannot be parsed. There is an extra "\r" returned by the server and openid4java has trouble parsing that.

**Comment by mmoayyed** [comment]
This is what is returned from CAS:

```
\r\nopenid.mode:id_res\nis_valid:true\n
``

when an HTTP post request is made. The extra "\r" is causing issues for the parser because it's using a Tokenizer and cant handle it.

**Comment by leleuj** [comment]
That's strange: the demo works for me out of the box (but I use the master with a CAS server 4.1.0-SNAPSHOT). I have the following HTTP requests:

http://localhost:8080/cas/login?<b>openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0</b>&openid.claimed_id=http%3A%2F%2Flocalhost%3A8080%2Fcas%2Fopenid%2Fleleuj&openid.identity=http%3A%2F%2Flocalhost%3A8080%2Fcas%2Fopenid%2Fleleuj&openid.return_to=http%3A%2F%2Flocalhost%3A8080%2Fdemoo%2FopenId.html&openid.realm=http%3A%2F%2Flocalhost%3A8080%2Fdemoo%2FopenId.html&openid.assoc_handle=1438590861217-0&openid.mode=checkid_setup&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fsreg%2F1.0&openid.sreg.optional=email%2Cfullname%2Cdob%2Cpostcode

http://localhost:8080/demoo/openId.html?openid.return_to=http%3A%2F%2Flocalhost%3A8080%2Fdemoo%2FopenId.html&openid.identity=http%3A%2F%2Flocalhost%3A8080%2Fcas%2Fopenid%2Fleleuj&openid.op_endpoint=http%3A%2F%2Flocalhost%3A8080%2Fcas%2Flogin&openid.assoc_handle=1438590861217-0&openid.mode=id_res&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=Gmog1Ym8iA8t2fzU1Z60KSEv%2FNLbOvYMr7kMK6TLX2w%3D&openid.claimed_id=http%3A%2F%2Flocalhost%3A8080%2Fcas%2Fopenid%2Fleleuj&openid.response_nonce=2015-08-03T08%3A35%3A06Z0&<b>openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0</b>

Indeed, the `openid.ns` parameter exists and defines that it's an OpenID 2.0 provider. I will update the CAS documentation accordingly.

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/1073

**Comment by mmoayyed** [comment]
I ran a clean build on master. Had very very little changes to make. Not sure why, but I always see that extra line break in the final post response.

**Comment by leleuj** [comment]
And does it work?

**Comment by mmoayyed** [comment]
With the above pull request, sure. Works just fine.

**Comment by mmoayyed** [comment]
Meant #1072
