### ISSUE TITLE
OpenID association does not work

### ISSUE THREAD

**Issue by leleuj** [Jasig/cas#1114]
Testing the 4.1.0-RC2, I got:

```
OPENID CLIENT DEMO 2015/09/03 13:32:33,499 ERROR [http-nio-8080-exec-8] org.openid4java.consumer.ConsumerManager - Error encountered during association attempt.
org.openid4java.message.MessageException: 0x100: Invalid Key-Value form, colon missing: 
	at org.openid4java.message.ParameterList.createFromKeyValueForm(ParameterList.java:209)
	at org.openid4java.consumer.ConsumerManager.call(ConsumerManager.java:618)
	at org.openid4java.consumer.ConsumerManager.associate(ConsumerManager.java:776)
	at org.openid4java.consumer.ConsumerManager.associate(ConsumerManager.java:658)
	at org.leleuj.MainController.confirm(MainController.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

The OpenID association does not work, which does not make any issue, except when the user wants to enter his identifier (`http://specs.openid.net/auth/2.0/identifier_select`).

I suspect some extra lines in the JSP files.

**Comment by leleuj** [comment]
The problem does not occur on my Mac with the RC3-SNAPSHOT. But I think it will happen on Windows.

**Comment by leleuj** [comment]
PR: https://github.com/Jasig/cas/pull/1115

I'll retest everything tomorrow on Windows to ensure the fix works.

**Comment by mmoayyed** [comment]
Merged via https://github.com/Jasig/cas/pull/1115
