### ISSUE TITLE
CachingPrincipalAttributesRepository cannot be instantiated

### ISSUE THREAD

**Issue by iigorr** [Jasig/cas#1208]
When following the [example on cached attribute release](http://jasig.github.io/cas/4.1.x/integration/Attribute-Release.html), I keep getting a `ConstraintDeclarationException` (see below).

I have tried to disable hibernate validation as described [here](https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html/validator-integration.html#example-using-validateonexecution), however this didn't have any effect at all.

The Problem seems to be the `@NotNull` annotation on the parameter in the `getAttributes` method. In fact I copied the class CachingPrincipalAttributesRepository to my overlay removing that annotation and it started working. 

```
Caused by: javax.validation.ConstraintDeclarationException: HV000151: A method overriding another method must not alter the parameter constraint configuration, but method public java.util.Map org.jasig.cas.authentication.principal.CachingPrincipalAttributesRepository.getAttributes(org.jasig.cas.authentication.principal.Principal) changes the configuration of public abstract java.util.Map org.jasig.cas.authentication.principal.PrincipalAttributesRepository.getAttributes(org.jasig.cas.authentication.principal.Principal).
	at org.hibernate.validator.internal.metadata.aggregated.rule.OverridingMethodMustNotAlterParameterConstraints.apply(OverridingMethodMustNotAlterParameterConstraints.java:34)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.assertCorrectnessOfConfiguration(ExecutableMetaData.java:448)
	at org.hibernate.validator.internal.metadata.aggregated.ExecutableMetaData$Builder.build(ExecutableMetaData.java:368)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BuilderDelegate.build(BeanMetaDataImpl.java:618)
	at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BeanMetaDataBuilder.build(BeanMetaDataImpl.java:521)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.createBeanMetaData(BeanMetaDataManager.java:184)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getOrCreateBeanMetaData(BeanMetaDataManager.java:207)
	at org.hibernate.validator.internal.metadata.BeanMetaDataManager.isConstrained(BeanMetaDataManager.java:151)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:193)
	at org.springframework.validation.beanvalidation.BeanValidationPostProcessor.doValidate(BeanValidationPostProcessor.java:106)
	at org.springframework.validation.beanvalidation.BeanValidationPostProcessor.postProcessAfterInitialization(BeanValidationPostProcessor.java:94)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	... 102 more
>
```

**Comment by mmoayyed** [comment]
What CAS version is this? 4.1?

**Comment by mmoayyed** [comment]
A temp workaround might be that you turn off/remove the principal repository, or you switch it to the default, if you don't need it.

**Comment by iigorr** [comment]
CAS Version is 4.1.0, Correct.
