### ISSUE TITLE
NPE when logout in Weblogic 12c

### ISSUE THREAD

**Issue by beuvenar** [Jasig/cas#1221]
We are using the CAS client 3.3.3 and Weblogic 12c (12.1.2.0.0) which uses servlets 3.0.
Each time a user logs out, a NullPointerException occurs in a internal class of Weblogic WebAppSecurity.java when the Servlet30LogoutStrategy calls the logout method on the request object (see stacktrace). 
After looking into the code of WebAppSecurity.java, it appears that Weblogic retrieves the session attached to the current request by using request.getSession(false) but the retrieved session is null since the session has already been invalidated by the SingleSignOutHandler before calling the Servlet30LogoutStrategy class.
Maybe there order of the calls could be changed in the SingleSignOutHandler class to invalidate the session after the logout method is called on the request object?

**Stacktrace:**

java.lang.NullPointerException
at weblogic.servlet.security.internal.WebAppSecurity.logout(WebAppSecurity.java:867)
at weblogic.servlet.internal.ServletRequestImpl.logout(ServletRequestImpl.java:3418)
at javax.servlet.http.HttpServletRequestWrapper.logout(HttpServletRequestWrapper.java:334)
at javax.servlet.http.HttpServletRequestWrapper.logout(HttpServletRequestWrapper.java:334)
at javax.servlet.http.HttpServletRequestWrapper.logout(HttpServletRequestWrapper.java:334)
at org.jasig.cas.client.session.SingleSignOutHandler$Servlet30LogoutStrategy.logout(SingleSignOutHandler.java:380)
at org.jasig.cas.client.session.SingleSignOutHandler.destroySession(SingleSignOutHandler.java:316)
at org.jasig.cas.client.session.SingleSignOutHandler.process(SingleSignOutHandler.java:212)
at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:99)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:166)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79)
at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3367)
at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3333)
at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2220)
at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2146)
at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2124)
at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1564)
at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:254)
at weblogic.work.ExecuteThread.execute(ExecuteThread.java:295)
at weblogic.work.ExecuteThread.run(ExecuteThread.java:254)

**Comment by leleuj** [comment]
Please open an issue on the CAS client project: https://github.com/Jasig/java-cas-client
