### ISSUE TITLE
JasperException and NoSuchFileException

### ISSUE THREAD

**Issue by dodolzg** [Jasig/cas#1235]
(1) I deploy war in tomcat, there is error in catalina.log:
22, 2015 11:59:44 org.apache.catalina.startup.Catalina initDirs
Cannot find specified temporary folder at /data/webapps/cas/temp

(2) When cas validates the service-ticket, there is error in localhost.log:
        Exception Processing ErrorPage[errorCode=500, location=/WEB-INF/view/jsp/errors.jsp]
org.apache.jasper.JasperException: /WEB-INF/view/jsp/errors.jsp (line: 21, column: 0) /WEB-INF/view/jsp/default/ui/includes/top.jsp 
(line: 25, column: 62) Unable to read TLD "META-INF/c.tld" from JAR file "jndi:/localhost/cas/WEB-INF/lib/standard-1.1.2.jar": java.
nio.file.NoSuchFileException: /data/webapps/cas/temp/jar_cache3066033100924365923.tmp
        at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42)
        at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:443)
        at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:89)
        at org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:324)
        at org.apache.jasper.compiler.Parser.parseIncludeDirective(Parser.java:357)
        at org.apache.jasper.compiler.Parser.parseXMLDirective(Parser.java:533)
        at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1429)
        at org.apache.jasper.compiler.Parser.parse(Parser.java:138)
        at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:242)
        at org.apache.jasper.compiler.ParserController.parse(ParserController.java:102)
        at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:198)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:373)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:353)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:340)
        at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:657)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:488)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:467)
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:338)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:428)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:201)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

(3) So I create the temp directory, and it works well.

      What is directory temp for? Need it be created? Can I config the path in configuration?

**Comment by leleuj** [comment]
Please use the CAS mailing lists for questions: http://jasig.github.io/cas/4.1.x/index.html

**Comment by dodolzg** [comment]
Thanks, I have sent mail to casgeneric-users@esup-portail.org, and then to sympa@esup-portail.org.

**Comment by leleuj** [comment]
I meant: https://groups.google.com/forum/?fromgroups#!forum/jasig-cas-user
