### ISSUE TITLE
ArrayStoreException in CasDelegatingLogger

### ISSUE THREAD

**Issue by frett** [Jasig/cas#1300]
I'm getting the following exception within the CasDelegatingLogger:

```
java.lang.ArrayStoreException: java.lang.String
	at org.slf4j.impl.CasDelegatingLogger.manipulateLogArguments(CasDelegatingLogger.java:92)
	at org.slf4j.impl.CasDelegatingLogger.trace(CasDelegatingLogger.java:156)
	at org.ldaptive.provider.ControlProcessor.processResponseControls(ControlProcessor.java:122)
	at org.ldaptive.provider.jndi.JndiConnection.processResponseControls(JndiConnection.java:789)
	at org.ldaptive.provider.jndi.JndiConnection.createResponse(JndiConnection.java:681)
	at org.ldaptive.provider.jndi.JndiConnection$JndiSearchIterator.hasNext(JndiConnection.java:1045)
	at org.ldaptive.SearchOperation.readResult(SearchOperation.java:153)
	at org.ldaptive.SearchOperation.executeSearch(SearchOperation.java:121)
	at org.ldaptive.SearchOperation.invoke(SearchOperation.java:101)
	at org.ldaptive.SearchOperation.invoke(SearchOperation.java:28)
	at org.ldaptive.AbstractOperation.execute(AbstractOperation.java:142)
	...
```

**Comment by frett** [comment]
this is in CAS 4.1.2 on Oracle Java 1.8.0
