### ISSUE TITLE
Unable to save Proxy Policy Options

### ISSUE THREAD

**Issue by nkovacne** [Jasig/cas#1426]
We're running CAS 4.1.1. We have a service which needs a Proxy Authentication Policy, so from the cas-management pane we select Regex instead of Refuse in Proxy Policy Options and we're unable to save it as an error is always shown, no matters what pattern is entered:

"Form validation has failed. Please fix the errors before attempting to save again."

We've even tried the easiest ones, like ^https?:// (as stated in: http://jasig.github.io/cas/4.1.x/installation/Service-Management.html#configure-proxy-authentication-policy), hello, a... it won't allow saving anything.

There's no event generated in any of the logs on hitting Save.

**Comment by mmoayyed** [comment]
Switch to 4.1.3 and report back

**Comment by nkovacne** [comment]
Same behavior. However, this time I have an entry in the log:

2016-01-07 12:42:03,162 ERROR [org.jasig.cas.services.web.RegisteredServiceSimpleFormController] - <java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid regex pattern specified for proxy policy: ^https?://
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid regex pattern specified for proxy policy: ^https?://
	at org.jasig.cas.services.web.RegisteredServiceSimpleFormController.saveService(RegisteredServiceSimpleFormController.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:775)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:168)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:162)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:120)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.jasig.inspektr.common.web.ClientInfoThreadLocalFilter.doFilter(ClientInfoThreadLocalFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid regex pattern specified for proxy policy: ^https?://
	at org.jasig.cas.services.web.beans.RegisteredServiceEditBean$ServiceData.toRegisteredService(RegisteredServiceEditBean.java:663)
	at org.jasig.cas.services.web.RegisteredServiceSimpleFormController.saveService(RegisteredServiceSimpleFormController.java:86)
	... 83 more
Caused by: java.lang.IllegalArgumentException: Invalid regex pattern specified for proxy policy: ^https?://
	at org.jasig.cas.services.web.beans.RegisteredServiceEditBean$ServiceData.toRegisteredService(RegisteredServiceEditBean.java:585)
	... 84 more

**Comment by mmoayyed** [comment]
I just tried to save an entry with a regex pattern here: https://jasigcasmgmt.herokuapp.com
And it was saved fine.  You can see the Test service yourself. Something else is going on.

**Comment by nkovacne** [comment]
Seems this is only reproducible when modifying an existing service adding the Proxy Options. I just tried adding a service with the Proxy Options and it's saved correctly; it's just modifications that fail.

**Comment by mmoayyed** [comment]
Even then, I can't reproduce it on this end. You can play around with the demo app. New and existing entries are saved correctly.

**Comment by mmoayyed** [comment]
You can try with 4.1.4-SNAPSHOT and see if that is the difference between us. I doubt it, since the demp app is rather old but it's worth a try.

**Comment by nkovacne** [comment]
Strange, indeed. Now I'm unable to even add directly the service with the Proxy Options. Same happens with 4.1.4-SNAPSHOT.

Does the regexp checker depend on a module defined in pom.xml? Maybe I'm using an old version of some package or something.

(P.S.: I tried defining a new service at the Test service, when the URL is in a string-form it's OK, if I enter a URL I get a "An error has occurred while attempting to save the service. Please try again later." error. Is that done on purpose?)

**Comment by mmoayyed** [comment]
> Maybe I'm using an old version of some package or something.

That is very likely. All CAS artifacts are grouped under the same version and released under the same. Your management overlay may be using an older CAS version. That is the overlay you should update. Not CAS itself. Remember that these are two separate apps. 

I'll play around with the test instance and see if I can duplicate this more.

**Comment by mmoayyed** [comment]
If you are referring to the service name, then yes. That is on purpose. the default registry is JSON, the name is used to construct the name of the JSON file. URL has invalid chars for a file name. Thus the error.

**Comment by mmoayyed** [comment]
Closing for now.

**Comment by nkovacne** [comment]
For what is worth, I'm adding the versions of dependencies that I have.

```
    <properties>
        <commons.dbcp.version>2.0</commons.dbcp.version>
        <cas.version>4.1.3</cas.version>
        <hibernate.version>4.3.10.Final</hibernate.version>
        <mysql.connector.version>5.1.6</mysql.connector.version>
        <xml.apis.version>1.4.01</xml.apis.version>
        <c3p0.version>0.9.5.1</c3p0.version>
    </properties>
```

Also, we're using the MySQL backend to store services (I doubt this has something to do with it, though, since it seems to happen at parsing time).

**Comment by nkovacne** [comment]
Any chance there's a workaround to insert the data manually in the DB meanwhile? I believe this is a blob field so it would be nice to know how to store it.

**Comment by mmoayyed** [comment]
You can either use the CAS API to save services, or use the REST api to add services. You cannot save blobs manually into the database.
