### ISSUE TITLE
Error when deploying CAS 4.1 in Weblogic because trust store file cannot be found

### ISSUE THREAD

**Issue by beuvenar** [Jasig/cas#1470]
Starting from release 4.1, the file applicationContext.xml  (which is in the folder WEB-INF/spring-configuration of cas-server-webapp WAR file) tries to create Spring bean (trustStoreSslSocketFactory) that take File object as constructor parameter for the trust store file. There is a fallback to classpath file (truststore.jks) if property  defining the path to the trust store file does not exist. In Weblogic, this fallback mechanism fails when deploying CAS server as WAR because Weblogic packages the classpath resource (truststore.jks) inside a JAR named _wl_cls_gen.jar during the deployment of the WAR file. Therefore the file truststore.jks is not accessible by Spring as a file when it tries to read it since it is not directly in the file system (because it is packaged inside the JAR _wl_cls_gen.jar) and a exception is thrown.
Note that the same problem occurs for the bean "serviceRegistryDao" in deployerConfigContext.xml because he tries to load a folder in the classpath as fallback mechanism and this folder is not accesible since it is inside the JAR file

Here is the stacktrace when deploying CAS 4.1 in Weblogic:

```
Related cause: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'trustStoreSslSocketFactory' defined in ServletContext resource [/WEB-INF/spring-configuration/applicationContext.xml]: Unsatisfied dependency expressed through constructor argument with index 0 of type [java.io.File]: Could not convert constructor argument value of type [java.lang.String] to required type [java.io.File]: Failed to convert value of type 'java.lang.String' to required type 'java.io.File'; nested exception is java.lang.IllegalArgumentException: Could not retrieve File for class path resource [truststore.jks]: class path resource [truststore.jks] cannot be resolved to absolute file path because it does not reside in the file system: zip:/u01/oracle/wls12130/user_projects/domains/base_domain/servers/AdminServer/tmp/_WL_user/eures-cas-server/rdqxt8/war/WEB-INF/lib/_wl_cls_gen.jar!/truststore.jks
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:140)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:838)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:678)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
	at weblogic.servlet.internal.EventsManager.executeContextListener(EventsManager.java:243)
	at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:200)
	at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:185)
	at weblogic.servlet.internal.WebAppServletContext.preloadResources(WebAppServletContext.java:1838)
	at weblogic.servlet.internal.WebAppServletContext.start(WebAppServletContext.java:2876)
	at weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.java:1661)
	at weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:823)
	at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:360)
	at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:356)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)
	at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:138)
	at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:216)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:211)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)
	at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:73)
	at weblogic.application.internal.flow.StartModulesFlow.activate(StartModulesFlow.java:24)
	at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:729)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:42)
	at weblogic.application.internal.BaseDeployment.activate(BaseDeployment.java:258)
	at weblogic.application.internal.SingleModuleDeployment.activate(SingleModuleDeployment.java:48)
	at weblogic.application.internal.DeploymentStateChecker.activate(DeploymentStateChecker.java:165)
	at weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(AppContainerInvoker.java:80)
	at weblogic.deploy.internal.targetserver.operations.AbstractOperation.activate(AbstractOperation.java:587)
	at weblogic.deploy.internal.targetserver.operations.ActivateOperation.activateDeployment(ActivateOperation.java:150)
	at weblogic.deploy.internal.targetserver.operations.ActivateOperation.doCommit(ActivateOperation.java:116)
	at weblogic.deploy.internal.targetserver.operations.AbstractOperation.commit(AbstractOperation.java:339)
	at weblogic.deploy.internal.targetserver.DeploymentManager.handleDeploymentCommit(DeploymentManager.java:846)
	at weblogic.deploy.internal.targetserver.DeploymentManager.activateDeploymentList(DeploymentManager.java:1275)
	at weblogic.deploy.internal.targetserver.DeploymentManager.handleCommit(DeploymentManager.java:442)
	at weblogic.deploy.internal.targetserver.DeploymentServiceDispatcher.commit(DeploymentServiceDispatcher.java:176)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.doCommitCallback(DeploymentReceiverCallbackDeliverer.java:195)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.access$100(DeploymentReceiverCallbackDeliverer.java:13)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer$2.run(DeploymentReceiverCallbackDeliverer.java:68)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:553)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)
```

Workaround is to define values for properties "http.client.truststore.file" and "service.registry.config.location".

**Comment by mmoayyed** [comment]
Properties are already defined for those two.

**Comment by mmoayyed** [comment]
As you correctly found out of course. The fix here is to instruct weblogic to not do that :)

**Comment by beuvenar** [comment]
Yes but this is only a workaround since by default these properties are not defined. It is therefore impossible to deploy CAS 4.1 in Weblogic with default configuration.

**Comment by mmoayyed** [comment]
They are defined by default. They are given a default value, which works for most sane containers. If you wish to change that behavior, the burden is on you to provide a value that overrides the default. That is actually something expected of you. We can tell you where to put your keystore and your json services file. Only you know that.

**Comment by beuvenar** [comment]
The point is that I don't care of these files. I would like to use the default ones provided in the cas-server-webapp WAR file but this does not work in Weblogic. So currently I am obliged to extract these files from the WAR file, to put it on the file system and to provide values for two properties that I don't care. But OK this is not a big deal and I can live with that.

**Comment by mmoayyed** [comment]
I am sorry to hear you had issues with this config. However, you should definitely care where your services are defined. You may not care how your truststore is configured for CAS. That is optional. As I said, we cannot change these values to anything else reasonably well/safe because we don't know how and on which platform and which container CAS is deployed. So yes, it is YOUR responsibility to figure out how to configure your deployment for your environment for your container for your platform. If you're annoyed by that responsibility, you have two options:

1. Contact weblogic and ask them to not mess around with applications artifacts.
2. It's possible weblogic has good reasons for that kind of packaging. Figure out how to turn that behavior off. 
3. Switch away from weblogic to something reasonable and sane that does not do that. And you'll be fine. 

We can't fix weblogic's issues for you. Only weblogic can do that. Applications control their classpath. If a container gets in the way of that, your most assured way to a fix would to tell the container to back off.
