### ISSUE TITLE
OAuth Tests failing on Travis

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#1475]
@leleuj I see:

```
org.jasig.cas.support.oauth.web.OAuth20ProfileControllerTests > verifyOKWithAuthorizationHeader FAILED
    org.pac4j.core.exception.TechnicalException: Cannot generate JWT
        at org.pac4j.jwt.profile.JwtGenerator.generate(JwtGenerator.java:135)
        at org.jasig.cas.support.oauth.web.OAuth20ProfileControllerTests.verifyOKWithAuthorizationHeader(OAuth20ProfileControllerTests.java:159)
        Caused by:
        com.nimbusds.jose.JOSEException: Couldn't create AES/GCM/NoPadding cipher: Cannot find any provider supporting AES/GCM/NoPadding
            at com.nimbusds.jose.crypto.AESGCM.encrypt(AESGCM.java:93)
            at com.nimbusds.jose.crypto.ContentCryptoProvider.encrypt(ContentCryptoProvider.java:169)
            at com.nimbusds.jose.crypto.DirectEncrypter.encrypt(DirectEncrypter.java:118)
            at com.nimbusds.jose.JWEObject.encrypt(JWEObject.java:353)
            at org.pac4j.jwt.profile.JwtGenerator.generate(JwtGenerator.java:127)
            ... 1 more
            Caused by:
            java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/GCM/NoPadding
                at javax.crypto.Cipher.getInstance(Cipher.java:529)
                at com.nimbusds.jose.crypto.AESGCM.encrypt(AESGCM.java:85)
                ... 5 more
```

See https://travis-ci.org/Jasig/cas/builds/103873924

If you look at the very beginning of the build, you see:

```bash
javac 1.7.0_80
before_install.1
0.00s$ ls ./etc
jce7.zip  jce8.zip  jetty
before_install.2
0.09s$ sudo unzip -j -o ./etc/jce7.zip *.jar -d `jdk_switcher home oraclejdk7`/jre/lib/security
Archive:  ./etc/jce7.zip
  inflating: /usr/lib/jvm/java-7-oracle/jre/lib/security/US_export_policy.jar  
  inflating: /usr/lib/jvm/java-7-oracle/jre/lib/security/local_policy.jar  
before_install.3
0.01s$ sudo ls `jdk_switcher home oraclejdk7`/jre/lib/security
blacklist	  java.security
cacerts		  javaws.policy
cacerts.original  local_policy.jar
javafx.policy	  trusted.libraries
java.policy	  US_export_policy.jar
```

Why the failures?

**Comment by mmoayyed** [comment]
Does this only work with JCE8, per https://github.com/pac4j/pac4j/issues/355? 

If so, does this mean CAS deployers MUST install JCE8/Java8?

**Comment by leleuj** [comment]
Good question! It should work with JCE7, but the pac4j build is configured with `openjdk8`, so I'm not sure.
The good knews is that per https://github.com/Jasig/cas/pull/1463, JWT will be removed and I hope that we'll have moved to JDK8 before I re-introduced JWT for OpenID Connect support.

**Comment by mmoayyed** [comment]
Very good. I guess this will be fixed once we switch to JDK8. I'll leave this issue open for now to track this.

**Comment by mmoayyed** [comment]
Fixed by switching travis to Java8
