### ISSUE TITLE
CAS 4.1.4 samlValidate does not work with CAS Client 3.1.8

### ISSUE THREAD

**Issue by luyseyal** [Jasig/cas#1489]
Our upstream vendor has a Groovy war with Spring Security bundled. It uses JA-SIG CAS Client 3.1.8.

It will not work with CAS 4.1.4 though it does work with 3.2.1.

Here is the error we're getting:
```
[Wed, 27-Jan-2016 @ 12:46:14.597] [http-bio-8180-exec-30] DEBUG org.jasig.cas.client.validation.Saml11TicketValidator  - Constructing validation url: https://testlogin.example.com/samlValidate?TARGET=https%3A%2F%2Ftestcasclient.example.com%2FTestService%2Fj_spring_cas_security_check

[Wed, 27-Jan-2016 @ 12:46:14.597] [http-bio-8180-exec-30] DEBUG org.jasig.cas.client.validation.Saml11TicketValidator  - Retrieving response from server.

[Wed, 27-Jan-2016 @ 12:46:14.694] [http-bio-8180-exec-30] DEBUG org.jasig.cas.client.validation.Saml11TicketValidator  - Server response: <?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><saml1p:Response InResponseTo="https://testcasclient.example.com/TestService/j_spring_cas_security_check" IssueInstant="2016-01-27T18:46:14.674Z" MajorVersion="1" MinorVersion="1" ResponseID="_123456" xmlns:saml1p="urn:oasis:names:tc:SAML:1.0:protocol"><saml1p:Status><saml1p:StatusCode Value="saml1p:Success"/></saml1p:Status><saml1:Assertion AssertionID="_123456" IssueInstant="2016-01-27T18:46:14.674Z" Issuer="localhost" MajorVersion="1" MinorVersion="1" xmlns:saml1="urn:oasis:names:tc:SAML:1.0:assertion"><saml1:Conditions NotBefore="2016-01-27T18:46:14.674Z" NotOnOrAfter="2016-01-27T18:46:44.674Z"><saml1:AudienceRestrictionCondition><saml1:Audience>https://testcasclient.example.com/TestService/j_spring_cas_security_check</saml1:Audience></saml1:AudienceRestrictionCondition></saml1:Conditions><saml1:AuthenticationStatement AuthenticationInstant="2016-01-27T18:46:14.439Z" AuthenticationMethod="urn:oasis:names:tc:SAML:1.0:am:unspecified"><saml1:Subject><saml1:NameIdentifier>usertest</saml1:NameIdentifier><saml1:SubjectConfirmation><saml1:ConfirmationMethod>urn:oasis:names:tc:SAML:1.0:cm:artifact</saml1:ConfirmationMethod></saml1:SubjectConfirmation></saml1:Subject></saml1:AuthenticationStatement><saml1:AttributeStatement><saml1:Subject><saml1:NameIdentifier>usertest</saml1:NameIdentifier><saml1:SubjectConfirmation><saml1:ConfirmationMethod>urn:oasis:names:tc:SAML:1.0:cm:artifact</saml1:ConfirmationMethod></saml1:SubjectConfirmation></saml1:Subject><saml1:Attribute AttributeName="MY_IDENTIFIER" AttributeNamespace="http://www.ja-sig.org/products/cas/"><saml1:AttributeValue xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xsd:string">ABCDEFGHIJKLMNOPQRSTUVWXYZ123456</saml1:AttributeValue></saml1:Attribute><saml1:Attribute AttributeName="authenticationMethod" AttributeNamespace="http://www.ja-sig.org/products/cas/"><saml1:AttributeValue xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xsd:string">LdapAuthenticationHandler</saml1:AttributeValue></saml1:Attribute><saml1:Attribute AttributeName="successfulAuthenticationHandlers" AttributeNamespace="http://www.ja-sig.org/products/cas/"><saml1:AttributeValue xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xsd:string">LdapAuthenticationHandler</saml1:AttributeValue></saml1:Attribute></saml1:AttributeStatement></saml1:Assertion></saml1p:Response></SOAP-ENV:Body></SOAP-ENV:Envelope>

[Wed, 27-Jan-2016 @ 12:46:14.696] [http-bio-8180-exec-30] ERROR org.opensaml.SAMLObject fromStream - caught an exception while parsing a stream: cvc-datatype-valid.1.2.1: 'https://testcasclient.example.com/TestService/j_spring_cas_security_check' is not a valid value for 'NCName'.

[Wed, 27-Jan-2016 @ 12:46:14.698] [http-bio-8180-exec-30] WARN  org.jasig.cas.client.validation.Saml11TicketValidationFilter  - org.jasig.cas.client.validation.TicketValidationException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 287; cvc-datatype-valid.1.2.1: 'https://testcasclient.example.com/TestService/j_spring_cas_security_check' is not a valid value for 'NCName'.
org.jasig.cas.client.validation.TicketValidationException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 287; cvc-datatype-valid.1.2.1: 'https://testcasclient.example.com/TestService/j_spring_cas_security_check' is not a valid value for 'NCName'.
        at org.jasig.cas.client.validation.Saml11TicketValidator.parseResponseFromServer(Saml11TicketValidator.java:94)
        at org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:188)
        at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:132)
        at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 287; cvc-datatype-valid.1.2.1: 'https://testcasclient.example.com/TestService/j_spring_cas_security_check' is not a valid value for 'NCName'.
        at org.jasig.cas.client.validation.Saml11TicketValidator.parseResponseFromServer(Saml11TicketValidator.java:50)
        ... 6 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 287; cvc-datatype-valid.1.2.1: 'https://testcasclient.example.com/TestService/j_spring_cas_security_check' is not a valid value for 'NCName'.
        ... 7 more

```

Thank you for any assistance!

Stephen Olander-Waters
Austin, Texas

**Comment by mmoayyed** [comment]
If the vendor is unable to update the client, you're welcome to switch to 4.1.5-SNAPSHOT and see if the recent fix resolves the issue for you.

**Comment by luyseyal** [comment]
Thanks for the quick response. I will let you know when I know something. For reference, is it this patch?
https://github.com/Jasig/cas/commit/14cc69259c29b30321e6ed5967a873bdee5049ce

**Comment by mmoayyed** [comment]
That's it. Yes.

**Comment by luyseyal** [comment]
We tried it on our test instance and it results in the exact same error.

**Comment by mmoayyed** [comment]
Can you post the entire sequence of events via logs?

**Comment by mmoayyed** [comment]
And how did you apply/test the patch?

**Comment by mmoayyed** [comment]
Also, please capture the SAML response CAS produces and paste it here. You can use Firefox's SAMLTracer.

**Comment by mmoayyed** [comment]
I should mention my testing of the patch included the client versions 3.2 and 3.3 and 3.4. Didnt go as far back as 3.1. You really want to be on 3.3 at least. There are a few parameter encoding issues with old versions of the client that have been fixed.

**Comment by luyseyal** [comment]
I think the sysadmin just updated to the snapshot Sonatype and grabbed the latest. It is autobuilt and deployed.

I'll have to sanitize the logs so you'll forgive me if this takes awhile. Don't want to shame anyone (vendor) or expose test instance information.

**Comment by luyseyal** [comment]
Is it OK if I use the logs from 4.1.4? He already undid the snapshot change.

**Comment by mmoayyed** [comment]
You are welcome to submit both versions of the logs. Feel free to sanitize as much as you can. 

The problem is that your service id, which is that long spring-security url contains characters such as ":" that are not valid for CommonName (CName). The patch attempts to sanitize that url so you would get testcasclient.example.com as the CName. I'd be curious to see where that fails and why.

**Comment by mmoayyed** [comment]
It may be that the SNAPSHOT is not correctly deployed to sonatype. At least I don't see the change there yet. Let me review.

**Comment by mmoayyed** [comment]
OK. I did confirm that SNAPSHOTs were not published when that patch went in. I restarted the process and now I do see it there on Sonatype. 

So please try again with the SNAPSHOT and let me know. You should be getting this jar: cas-server-support-saml-4.1.5-20160127.223508-3.jar

**Comment by mmoayyed** [comment]
Link https://oss.sonatype.org/content/repositories/snapshots/org/jasig/cas/cas-server-support-saml/4.1.5-SNAPSHOT/

**Comment by luyseyal** [comment]
@spacepants  (Paging admin to the thread. Will delete post if this does not work)

**Comment by luyseyal** [comment]
Sorry for the delay, @mmoayyed but IT WORKED! 4.1.5-SNAPSHOT with your patch successfully worked with 3.1.8. 

Any kind of ETA on a formal release for 4.1.5?

**Comment by luyseyal** [comment]
FWIW, I don't expect the vendor to update this CAS code for at least 18 months.

**Comment by mmoayyed** [comment]
Excellent. Feb 19. You could checkout the milestone dates on github. Maintenance releases go out every month.

**Comment by luyseyal** [comment]
Thanks, @mmoayyed !
