### ISSUE TITLE
CAS Management crash

### ISSUE THREAD

**Issue by frett** [Jasig/cas#1491]
I'm seeing a crash caused by Inspektr in the cas-management war compiled from master. Investigating now, but wanted to log it in case I got sidetracked.

```
2016-01-28 16:06:28,301 ERROR [org.jasig.cas.services.web.RegisteredServiceSimpleFormController] - <java.lang.IllegalArgumentException: 'principal' cannot be null.
Check the correctness of @Audit annotation at the following audit point: execution(public abstract org.jasig.cas.services.RegisteredService org.jasig.cas.services.ServicesManager.save(org.jasig.cas.services.RegisteredService))
java.lang.RuntimeException: java.lang.IllegalArgumentException: 'principal' cannot be null.
Check the correctness of @Audit annotation at the following audit point: execution(public abstract org.jasig.cas.services.RegisteredService org.jasig.cas.services.ServicesManager.save(org.jasig.cas.services.RegisteredService))
	at org.jasig.cas.services.web.RegisteredServiceSimpleFormController.saveService_aroundBody0(RegisteredServiceSimpleFormController.java:78)
	at org.jasig.cas.services.web.RegisteredServiceSimpleFormController$AjcClosure1.run(RegisteredServiceSimpleFormController.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
	at org.jasig.cas.services.web.RegisteredServiceSimpleFormController.saveService(RegisteredServiceSimpleFormController.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.jasig.inspektr.common.web.ClientInfoThreadLocalFilter.doFilter(ClientInfoThreadLocalFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: 'principal' cannot be null.
Check the correctness of @Audit annotation at the following audit point: execution(public abstract org.jasig.cas.services.RegisteredService org.jasig.cas.services.ServicesManager.save(org.jasig.cas.services.RegisteredService))
	at org.jasig.inspektr.audit.AuditActionContext.assertNotNull(AuditActionContext.java:80)
	at org.jasig.inspektr.audit.AuditActionContext.<init>(AuditActionContext.java:62)
	at org.jasig.inspektr.audit.AuditTrailManagementAspect.executeAuditCode(AuditTrailManagementAspect.java:153)
	at org.jasig.inspektr.audit.AuditTrailManagementAspect.handleAuditTrail(AuditTrailManagementAspect.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy1225.save(Unknown Source)
	at org.jasig.cas.services.web.RegisteredServiceSimpleFormController.saveService_aroundBody0(RegisteredServiceSimpleFormController.java:69)
	... 50 more
>
```

**Comment by mmoayyed** [comment]
In my experience, this usually is not the cause. Something else is eating up the real error.

**Comment by frett** [comment]
it appears to be an AOP error somewhere internally, will have to debug more later.

**Comment by frett** [comment]
in a debugger the exception that I'm seeing thrown internally is:

```
java.lang.NoSuchMethodError: org.jasig.inspektr.audit.AuditTrailManagementAspect.aspectOf()Lorg/jasig/inspektr/audit/AuditTrailManagementAspect;
```

saw one forum post suggesting it is related to the AspectJ weaving of the class. going to check compile time & runtime weaving config.

**Comment by mmoayyed** [comment]
I know what this is. Run `gradle clean` once and then run the build again.

**Comment by frett** [comment]
just did a clean & build and still seeing the exception. I'll do more digging when I have a chance.

What I'm doing to cause it is deploying the stock cas-management war with no customizations, the exception is thrown when I edit a service and click save.

**Comment by mmoayyed** [comment]
FWIW, I am not seeing this. Fresh off of master. I am fairly certain the issue is with leftover artifacts that were skipped during the aspectj compilation phase. Did you clean everything from the root, or everything from the management webapp?

**Comment by frett** [comment]
K, probably just something in my environment then. I ran `./gradlew clean :cas-management-webapp:build` I'll try using git clean and also flushing out my local artifact repo. I'll reopen if I still have issues.

**Comment by mmoayyed** [comment]
If it helps, this is what I run:

```
CD cas-server/cas-management-webapp
gradle build --parallel -x test -DskipCheckstyle=true -x javadoc -DskipAspectJ=true -DskipFindbugs=true --console rich --max-workers 8 jettyRunWar
```

**Comment by frett** [comment]
I wonder if it's a tomcat vs jetty thing

**Comment by frett** [comment]
@mmoayyed re-run your test, but don't disable AspectJ with `-DskipAspectJ=true`

things work for me without aspectj compile time weaving enabled, but break when it is enabled

**Comment by mmoayyed** [comment]
OK. I'll check.

**Comment by mmoayyed** [comment]
Confirmed. Thanks for the find. Let's look further.

**Comment by mmoayyed** [comment]
So my current working theory is that this is an issue with the build, and not so much the code. You weave, problems. You don't weave, no problems. Since the weaver is fine, and the code is fine (as far as I can tell), then it's something in between. I am massaging the gradle build a bit to see if that is in fact true.

**Comment by mmoayyed** [comment]
I am also half tempted to remove the weaving code form the build. It's only job is to provide TRACE level logs. I am debating whether that actually is useful for the majority, or can we make do with DEBUG only.

**Comment by mmoayyed** [comment]
Yup. Solved it. PR upcoming.

**Comment by frett** [comment]
I like the concept of compile time weaving, it means a little bit less overhead at runtime because there isn't a need to create dynamic proxy beans.

But I think long term it comes down to which model is easier to maintain and support

**Comment by mmoayyed** [comment]
OK. I do NOT see this in 4.2. Are you sure you were not on master when you were testing this? 

I made sure artifacts are weaved. I can edit and save entries just fine, which makes sense because the build bug was really in master when we reorged the dependencies.

**Comment by frett** [comment]
I was on master, I hadn't tried on 4.2

**Comment by frett** [comment]
sorry about that confusion, I was just asking if it was necessary on 4.2, I didn't have a chance to check if it worked there or not

**Comment by mmoayyed** [comment]
No worries. That is a relief actually. If you could do a quick check and LMK, I'd be happy to proceed with RC2 some time next week.

**Comment by frett** [comment]
alright, let me go test

**Comment by frett** [comment]
tests fine on both jetty and tomcat for me

**Comment by tduehr** [comment]
I was running up against a similarly opaque error with the OAuth service class in the mgmt app. Fixed by adding OAuth support as a dependency. Perhaps this service class should be moved to core-util or split out of the main OAuth module and added as a dependency to mgmt.

**Comment by tduehr** [comment]
I also was seeing this exact error on login, after success against ldap, but before `authenticate()` completed. Removing the spring audit config cleared this to reveal the actual error but I don't remember what right now.

**Comment by leleuj** [comment]
@tduehr : the management webapp has a dependency on the OAuth module. In 4.2 and master, the OAuth module was split into two modules: a core one and a main one. You shouldn't have any problem with OAuth from the management webapp.
