### ISSUE TITLE
Identifier of "RegisteredServiceImpl_Properties" is too long for Oracle

### ISSUE THREAD

**Issue by ikogan** [Jasig/cas#1652]
When starting up CAS 4.2.0 with a JPA service registry handler on Oracle 12.1c, Hibernate is unable to update the schema with:

```
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Unable to execute schema management to JDBC target [create table RegisteredServiceImpl_Properties (AbstractRegisteredService_id number(19,0) not null, properties_id number(19,0) not null, properties_KEY varchar2(255 char) not null, primary key (AbstractRegisteredService_id, properties_KEY))]
	at org.hibernate.tool.schema.internal.TargetDatabaseImpl.accept(TargetDatabaseImpl.java:59)
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.applySqlString(SchemaMigratorImpl.java:421)
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.applySqlStrings(SchemaMigratorImpl.java:410)
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.createTable(SchemaMigratorImpl.java:226)
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.doMigrationToTargets(SchemaMigratorImpl.java:167)
	at org.hibernate.tool.schema.internal.SchemaMigratorImpl.doMigration(SchemaMigratorImpl.java:60)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:129)
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:97)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:481)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:444)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:802)
	... 63 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
...
```

This is running in Tomcat 8 with the following relevant `cas.properties` settings:

```
svcreg.database.dialect=org.hibernate.dialect.Oracle12cDialect
svcreg.database.batchSize=20
svcreg.database.ddl.auto=update
```

And `deployerConfigContext.xml` snippet:

```xml
    <bean id="dataSourceService" class="org.springframework.jndi.JndiObjectFactoryBean"
          p:jndiName="java:comp/env/jdbc/ou_cas"/>

    <alias name="jpaServiceRegistryDao" alias="serviceRegistryDao" />
```

Note that, `web.xml` was modified to load the customized XML files last:

```xml
    <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>
            classpath*:/META-INF/spring/*.xml
            /WEB-INF/spring-configuration/*.xml
            /WEB-INF/deployerConfigContext.xml
        </param-value>
    </context-param>
```

Steps to reproduce:
1. Setup an Oracle 12 database, XE works fine. Docker containers work great.
2. Create a schema.
3. Setup CAS with a JPA Service Registry.

**Comment by mmoayyed** [comment]
@frett might this be something you could look into?

**Comment by dima767** [comment]
Just say that we don't support Oracle and close this ticket...

I'm just joking, of course :-)

**Comment by ikogan** [comment]
I've fixed it by simply renaming the JoinTable and am prepping a PR but I'm concerned with how existing users in other databases will deal with that change. Since this is simply using Hibernate's DDL update mechanism, we don't really have a controlled way to migrate. It doesn't seem like Hibernate dialects are able to adjust the identifier length and the general recommendations have been to simply rename your table in your entity mapping.

I really wish I could simply not support Oracle...

**Comment by frett** [comment]
@ikogan raised up all the valid points, there isn't a good migration path for users that may already be using `RegisteredServiceProperties` with JPA. But this change is required for Oracle to work.

With that said I think this change should be fine to merge and back port to 4.1.x (since we included properties there already). We haven't exposed properties on the admin UI yet, so I highly doubt anyone is using this feature with the JPA service registry yet and changing the table name now won't break existing data.

**Comment by frett** [comment]
It would be nice if we could get some form of lint check to validate database name limits to prevent this from happening in the future.

**Comment by frett** [comment]
merged and back/forward ported
