### ISSUE TITLE
Analyze the use of ticket delegators; remove if necessary

### ISSUE THREAD

**Issue by dima767** [Jasig/cas#1672]
With the current `5.0.0-SNAPSHOT` and enabled HazelcastTicketRegistry, it is severely broken with the following:

1. First, the following exception shows up during the "cleaner business":

```java
...
2016-04-04 09:51:56,151 ERROR [org.quartz.core.ErrorLogger] - <An error occured instantiating job to be executed. job= 'DEFAULT.HazelcastTicketRegistrya06ead4b-eb67-473f-b984-9f4b60e2ef1e'
org.quartz.SchedulerException: Job instantiation failed [See nested exception: java.lang.InstantiationException: org.jasig.cas.ticket.registry.HazelcastTicketRegistry]
	at org.springframework.scheduling.quartz.AdaptableJobFactory.newJob(AdaptableJobFactory.java:45)
	at org.quartz.core.JobRunShell.initialize(JobRunShell.java:127)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:375)
Caused by: java.lang.InstantiationException: org.jasig.cas.ticket.registry.HazelcastTicketRegistry
	at java.lang.Class.newInstance(Class.java:427)
	at org.springframework.scheduling.quartz.AdaptableJobFactory.createJobInstance(AdaptableJobFactory.java:58)
	at org.springframework.scheduling.quartz.SpringBeanJobFactory.createJobInstance(SpringBeanJobFactory.java:74)
	at org.jasig.cas.util.CasSpringBeanJobFactory.createJobInstance(CasSpringBeanJobFactory.java:39)
	at org.springframework.scheduling.quartz.AdaptableJobFactory.newJob(AdaptableJobFactory.java:41)
	... 2 more
Caused by: java.lang.NoSuchMethodException: org.jasig.cas.ticket.registry.HazelcastTicketRegistry.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 6 more
```

2. Then during the service ticket generation it fails with the following:

```java
...
04-Apr-2016 09:52:35.857 SEVERE [http-nio-8143-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [cas] in context with path [/cas] threw exception [Request processing failed; nested exception is org.springframework.webflow.execution.ActionExecutionException: Exception thrown executing org.jasig.cas.web.flow.GenerateServiceTicketAction@13801e21 in state 'generateServiceTicket' of flow 'login' -- action execution attributes were 'map[[empty]]'] with root cause
 java.io.NotSerializableException: org.jasig.cas.ticket.registry.HazelcastTicketRegistry
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:242)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:41)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:138)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:116)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:104)
	at com.hazelcast.map.impl.proxy.MapProxySupport.toData(MapProxySupport.java:944)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.set(MapProxyImpl.java:179)
	at org.jasig.cas.ticket.registry.HazelcastTicketRegistry.addTicket(HazelcastTicketRegistry.java:74)
	at org.jasig.cas.AbstractCentralAuthenticationService.updateTicket(AbstractCentralAuthenticationService.java:257)
	at org.jasig.cas.CentralAuthenticationServiceImpl.evaluatePossibilityOfMixedPrincipals(CentralAuthenticationServiceImpl.java:180)
	at org.jasig.cas.CentralAuthenticationServiceImpl.grantServiceTicket(CentralAuthenticationServiceImpl.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
...
```
Environment details:

`Tomcat 8.0.32`

```bash
******************** Welcome to CAS *******************
CAS Version: 5.0.0-SNAPSHOT
Build Date/Time: 2016-04-03T15:16:12Z
Java Home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_45
OS Architecture: x86_64
OS Name: Mac OS X
OS Version: 10.11.3
*******************************************************
```

Steps to re-produce:

1. Clone https://github.com/cas-projects/cas-issues/tree/master/cas-issue-1672 and build with `mvn clean package` (make sure that the local .m2 cache is clean so it pulls the latest snapshot version)

2. Deploy the cas.war

3. Login with `?service=https://www.google.com`

**Comment by dima767** [comment]
OK, after a debugging session, I've traced it to this:

at the point of failure here: https://github.com/Jasig/cas/blob/master/cas-server-integration-hazelcast/src/main/java/org/jasig/cas/ticket/registry/HazelcastTicketRegistry.java#L74

that encTicket reference is actually an instance of ticket delegator which in turn contains an instance of this ticket registry, which obviously is not serializable. First, I don't quite get this ticket delegator voodo, and second, then this code is wrong - we need to add a "dance" here to test the instance type and if it is a delegator, get the ticket out of it to store THAT in the HZ map. I have a suspicion that other service registry impls that rely on serializable items might have the similar bug.

But then again, I am not sure of this ticket delegator complexity and why it's needed.

**Comment by mmoayyed** [comment]
Found, duplicated and fixed.

**Comment by mmoayyed** [comment]
- https://github.com/Jasig/cas/blob/letsboot/cas-server-integration-hazelcast/src/main/java/org/jasig/cas/ticket/registry/HazelcastTicketRegistry.java#L40

- https://github.com/Jasig/cas/blob/letsboot/cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/AbstractTicketDelegator.java#L22

**Comment by dima767** [comment]
OK, that's fine. But for clearer understanding:

1) Why do we need a default ctor just to satisfy this cleaner business? (as you figured out already, I'm not a huge fan of this external cleaner) ;-)

2) Yeah, transient registry, sure, but the bigger picture - what is this delegator stuff? Why do we need it? And why are we storing the delegator instances in the cache/grid instead of the tickets instances themselves? I guess I don't see a big picture use case for it and where is it (delegator wrappers) used heavily in the CAS server guts.

**Comment by mmoayyed** [comment]
1) The default ctor is likely required by the quartz scheduler that starts the cleaner process. The job, I suppose, is created reflectively and so it needs that ctor. The default behavior of the cleaner I think is be active, but there is a setting that can be used to turn it off. 

2) Dont know, TBH. Might be a good candidate for removal. At least initial scans don't show anything relevant or important (or it may be that it was needed at some point and future refacts made it unnecessary) @frett might know more, since I think at a minimum, delegators do serve a purpose for JPA one way or other. If not, we shall remove.

**Comment by dima767** [comment]
+1 for removing any YAGNI craft

**Comment by mmoayyed** [comment]
Needless to say, I focused on the problem at hand but we likely need further analysis on this to see what might break or not, if we removed and did away with the delegators.

**Comment by mmoayyed** [comment]
At the very least, it would be useful to document the purpose somewhere :)

**Comment by dima767** [comment]
Let me tell you - when I stepped through the debugger and found out what is causing this, my very first reflex was - "Oh, let's just mark that registry as transient" ;-) Then I backed off. Many question and not knowing the big picture - I hesitated. We are storing thee delegators instead of the tickets here. What are the implications of that, etc.?

**Comment by dima767** [comment]
I blame @frett LOL... Just kidding, of course, but I am more than anxious to remove this delegator craft (of course we can't do it willy-nilly, but need to understand the original intent and see if it's not used as intended, etc.)

**Comment by mmoayyed** [comment]
Best guess without further analysis is that it may have had something to do with registries that do binary serialization on the wire like Memcached and Hazelcast, where CAS would want to delegate to a real ticket instance as opposed to what's reconstructed back from the wire. They may have served their purpose, and we could try to see what it might take to remove them. @leleuj might know about the memcached stuff more.

**Comment by frett** [comment]
I don't think any registry should be storing the delegators. I know on the JPA side we need the delegators to automatically cascade state updates back into the registry. I'm not sure the needs of the other registries enough to know if they monitor updates to the tickets after they are loaded and then push those changes back into the registry automatically or not.

**Comment by mmoayyed** [comment]
Ah, I think I know! 

I think it used to be true that when a registry did serialization, it simply just put the ticket id only on the wire as a String to avoid serialization issues. When it reconstructed the ticket id back from the registry as a String, it created a ticket delegator for that ticket id and put out the actual Java object. I think today's design requires that all tickets be serializable and then the ticket object as a whole is serialized, thus we might not need the delegators at all for that reason. 

JPA might be different; maybe we could isolate the use case of delegators to JPA only.

**Comment by dima767** [comment]
I know for sure that Hazelcast impl could care less for all of that. So if it turns out to be used by a single impl for a very specific purpose, I'd re-design it to be isolated only to that impl and not "poison" the tickets domain with this delegator stuff

**Comment by mmoayyed** [comment]
Updated the ticket, assigned to @frett for the time being.

**Comment by dima767** [comment]
OK @mmoayyed , @frett I'm going to give it a try this week. Since I don't know all the intricate details and purpose of the delegators, I'm going to employ a blunt strategy - delete all the delegator classes, fix the compilation errors and run the entire build to make sure all the tests pass. How does that sound? If not satisfactory, I'll back off from this one ;-)

**Comment by mmoayyed** [comment]
Sounds good. That's what I'd do too :)
