### ISSUE TITLE
[CAS-1080] Can't deploy default cas.war on JBoss AS7 or Jonas 5.2.1

### ISSUE THREAD

**Issue by mmoayyed** [Jasig/cas#538]
I downloaded latest CAS and build cas.war. When I deploy it in Tomcat, everything works. When I deploy it in JBoss AS 7.0.2 or Jonas (or probably other app server) it doesn't work.

The exception:

``````````
13:46:54,406 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC00001: Failed to start service
jboss.persistenceunit."cas.war#CasPersisten
ce": org.jboss.msc.service.StartException in service jboss.persistenceunit."cas.war#CasPersistence": Failed
to start service
at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1780)
[jboss-msc-1.0.1.GA.jar:1.0.1.GA]
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [:1.6.0_22]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [:1.6.0_22]
at java.lang.Thread.run(Thread.java:662) [:1.6.0_22]
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: CasPersistence] Unable to build EntityManagerFactory
at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:908)
at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:884)
at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java:73)
at org.jboss.as.jpa.service.PersistenceUnitService.createContainerEntityManagerFactory(PersistenceUnitService.java:143)
at org.jboss.as.jpa.service.PersistenceUnitService.start(PersistenceUnitService.java:77)
at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1824)
[jboss-msc-1.0.1.GA.jar:1.0.1.GA]
at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1759)
[jboss-msc-1.0.1.GA.jar:1.0.1.GA]
... 3 more
Caused by: org.hibernate.HibernateException: Connection cannot be null when 'hibernate.dialect' not set
at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:97)
at org.hibernate.service.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:67)
at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:170)
at org.hibernate.service.internal.BasicServiceRegistryImpl.configureService(BasicServiceRegistryImpl.java:80)
at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:145)
at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:118)
at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:70)
at org.hibernate.cfg.Configuration.buildSettingsInternal(Configuration.java:2253)
at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2249)
at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1720)
at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:76)
at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:899)
... 9 more
``````````

What to do?

Environment: JBoss AS7.0.2
Jonas 5.2.1

Reported by: Igor Spasic, id: igorspasic

Created: Thu, 22 Dec 2011 05:51:25 -0700

Updated: Fri, 28 Jun 2013 05:30:08 -0700

JIRA: https://issues.jasig.org/browse/CAS-1080

I was able to resolve these issues by disabling the JPA support built into JBoss AS 7 for this persistence unit ("CasPersistence") by adding the following to the "/WEB-INF/classes/META-INF/persistence.xml" from the war:

<properties>
<property name="jboss.as.jpa.managed" value="false"/>
</properties>

After doing that, one problem remained: the log4j.xml file cannot be found on the war classpath. This was resolved by commenting out the Spring bean that sets up the log4j config in the cas war (file location: "/WEB-INF/spring-configuration/log4jConfiguration.xml"):

<beans xmlns="http://www.springframework.org/schema/beans"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns![tongue.gif][]="http://www.springframework.org/schema/p"
xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd">

<description>
Log4J initialization. Configuration options are sourced from cas.properties. This allows deployers to externalize
both cas.properties and log4j.xml, so that a single cas.war file can be deployed to multiple tiers or hosts without
having to do any post configuration. This approach helps to preserve configuration between upgrades.

Deployers should not have to edit this file.
</description>

</beans>

Now your cas war should deploy and work correctly on JBoss AS 7.1.1.Final.

Remark: You still need to set SSL for the JBoss server to be able to use all the features of the cas protocol that require https connections.

[tongue.gif]: https://issues.jasig.org/images/icons/emoticons/tongue.gif

**Comment by mmoayyed** [comment]
The solution is presented in the issue description.
