### ISSUE TITLE
REST API endpoint /v1/tickets appears to lose credential request parameters

### ISSUE THREAD

**Issue by wuwx** [Jasig/cas#886]
may be add filter, and use httpServerletRequest.getParamsMap();
so restlet lost request params

**Comment by bartolomeon** [comment]
I can confirm that restlet api - /v1/tickets doesn't work - it fails because no parameters get to the authenticating handler. It is the same for 4.0.0 as for 4.0.1.
The reason seems to be the filter:
org.jasig.cas.security.RequestParameterPolicyEnforcementFilter

after switching it off in web.xml I can get the TGT via Rest interface.

**Comment by mmoayyed** [comment]
which parameters are these?

**Comment by bartolomeon** [comment]
Don't understand the question - which parameters do you mean?

Actually, seems that just a presence of this filter in the chain causes this effect. I have debugged it a bit, the filter doesn't do anything in its body which would break it. It gets a FacadeRequest, gets getParameterMap() do some comparisions against the values in the map and passes the same instance further on. If something was wrong with params it would throw.
So, in theory - it's presence shouldn't make any difference, but somehow it does...

**Comment by mmoayyed** [comment]
The issue description somewhat vaguely says: "lost params". My question is, which parameters are these? Can you describe your test scenario? The filter should only attempt stop requests that are seemingly badly formatted so I am curious what the request looks like that would have the filter intercept it.

**Comment by bartolomeon** [comment]
The fitler does not intercept anything, it is just an observation I made, that when I comment out the mapping for this particular filter - it all works. Tried to debug, thinking it e.g. wraps the request, but the code is simple and should not have any effect. 

The particular error I get is, that for the request:


curl -v -X POST  "http://localhost:8080/cas/v1/tickets" --data "username=cons1&password=pass&additionalParam1=paramvalue"


I am getting this behavior:


2015-04-13 10:50:43,522 DEBUG [org.jasig.cas.integration.restlet.TicketResource] - Obtaining credentials...
2015-04-13 10:50:43,943 DEBUG [org.jasig.cas.integration.restlet.TicketResource] - 
2015-04-13 10:50:44,134 INFO [org.jasig.cas.authentication.PolicyBasedAuthenticationManager] - UserManagmentRestUsernamePasswordAuthenticationHandler failed authenticating null+password
2015-04-13 10:50:44,324 INFO [com.github.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - Audit trail record BEGIN
=============================================================
WHO: audit:unknown
WHAT: supplied credentials: [null+password]
ACTION: AUTHENTICATION_FAILED
APPLICATION: CAS
WHEN: Mon Apr 13 10:50:44 CEST 2015
CLIENT IP ADDRESS: 127.0.0.1
SERVER IP ADDRESS: 127.0.0.1
=============================================================


2015-04-13 10:50:44,694 INFO [com.github.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - Audit trail record BEGIN
=============================================================
WHO: audit:unknown
WHAT: 1 errors, 0 successes
ACTION: TICKET_GRANTING_TICKET_NOT_CREATED
APPLICATION: CAS
WHEN: Mon Apr 13 10:50:44 CEST 2015
CLIENT IP ADDRESS: 127.0.0.1
SERVER IP ADDRESS: 127.0.0.1
=============================================================


2015-04-13 10:50:44,696 ERROR [org.jasig.cas.integration.restlet.TicketResource] - 1 errors, 0 successes
org.jasig.cas.authentication.AuthenticationException: 1 errors, 0 successes
	at org.jasig.cas.authentication.PolicyBasedAuthenticationManager.authenticateInternal(PolicyBasedAuthenticationManager.java:248)
	at org.jasig.cas.authentication.PolicyBasedAuthenticationManager.authenticate(PolicyBasedAuthenticationManager.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
	at com.github.inspektr.audit.AuditTrailManagementAspect.handleAuditTrail(AuditTrailManagementAspect.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
	at org.perf4j.aop.AbstractTimingAspect$1.proceed(AbstractTimingAspect.java:47)
	at org.perf4j.aop.AgnosticTimingAspect.runProfiledMethod(AgnosticTimingAspect.java:53)
	at org.perf4j.aop.AbstractTimingAspect.doPerfLogging(AbstractTimingAspect.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy807.authenticate(Unknown Source)
	at org.jasig.cas.CentralAuthenticationServiceImpl.createTicketGrantingTicket(CentralAuthenticationServiceImpl.java:531)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
	at com.github.inspektr.audit.AuditTrailManagementAspect.handleAuditTrail(AuditTrailManagementAspect.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:80)
	at org.perf4j.aop.AbstractTimingAspect$1.proceed(AbstractTimingAspect.java:47)
	at org.perf4j.aop.AgnosticTimingAspect.runProfiledMethod(AgnosticTimingAspect.java:53)
	at org.perf4j.aop.AbstractTimingAspect.doPerfLogging(AbstractTimingAspect.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:65)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy808.createTicketGrantingTicket(Unknown Source)
	at org.jasig.cas.integration.restlet.TicketResource.acceptRepresentation(TicketResource.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:503)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:552)
	at org.restlet.resource.ServerResource.post(ServerResource.java:1185)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:437)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:350)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:951)
	at org.restlet.resource.Finder.handle(Finder.java:246)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Router.doHandle(Router.java:431)
	at org.restlet.routing.Router.handle(Router.java:648)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:155)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.routing.Filter.doHandle(Filter.java:159)
	at org.restlet.routing.Filter.handle(Filter.java:206)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:211)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:84)
	at org.restlet.Application.handle(Application.java:381)
	at org.restlet.ext.servlet.ServletAdapter.service(ServletAdapter.java:206)
	at org.restlet.ext.spring.RestletFrameworkServlet.doService(RestletFrameworkServlet.java:124)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:838)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:812)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:439)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.jasig.cas.security.RequestParameterPolicyEnforcementFilter.doFilter(RequestParameterPolicyEnforcementFilter.java:211)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.github.inspektr.common.web.ClientInfoThreadLocalFilter.doFilter(ClientInfoThreadLocalFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by bartolomeon** [comment]
So, the 'lost params' are the username/password which is later needed ( you can see 'null+password' in the log)

**Comment by mmoayyed** [comment]
Excellent, thank you for the report. Now we have test case to debug this for! I'll try to run through this sequence shortly and see what may be causing this.

**Comment by mmoayyed** [comment]
Confirmed bug.

**Comment by mmoayyed** [comment]
This seems to be an issue with the filter consuming the request input stream. Since restlet in CAS attempts to re-read the input stream to construct the post parameters, it comes up empty handed. I have played around with a few solutions none of which have proved effective. I recommend that you use the new support-rest module in CAS which does not exhibit the same problem. We have deprecated the restlet module and will not continue with any new dev. 

A temporary solution might be to remove the filter, but that might leave your CAS instance exposed, sadly.

**Comment by mbohun** [comment]
well @mmoayyed, the only problem with `support-rest` module is that that is not part of the current stable `4.0.x` stream, you added it to `4.1.0-SNAPSHOT`; and there is nothing about restlet being deprecated in the official CAS guide for the stable `4.0.x` stream either: https://jasig.github.io/cas/4.0.x/protocol/REST-Protocol.html 

 (i just ran into this issue/problem) 10minutes ago:

client side:
```BASH
bash-3.2$ curl -i --http1.0 -X POST --data "username=joe&password=test" https://nci-cas4.ala.org.au/cas/v1/tickets
HTTP/1.1 400 Bad Request
Date: Tue, 04 Aug 2015 09:36:35 GMT
Server: Restlet-Framework/2.1.0
Accept-Ranges: bytes
Content-Type: text/html;charset=UTF-8
Content-Length: 404
Connection: close

<html>
<head>
   <title>Status page</title>
</head>
<body style="font-family: sans-serif;">
<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Bad Request</p>
<p>1 errors, 0 successes</p>
<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1">here</a>.<br>
Please continue your visit at our <a href="/">home page</a>.
</p>
</body>
</html>
```

in catalina.out:
```
2015-08-04 09:36:35,879 DEBUG [org.jasig.cas.integration.restlet.TicketResource] - <Obtaining credentials...>
2015-08-04 09:36:35,879 DEBUG [org.jasig.cas.integration.restlet.TicketResource] - <>
2015-08-04 09:36:35,880 INFO [org.jasig.cas.authentication.PolicyBasedAuthenticationManager] - <QueryDatabaseAuthenticationHandler failed authenticating null+password>
2015-08-04 09:36:35,880 INFO [com.github.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
=============================================================
WHO: audit:unknown
WHAT: supplied credentials: [null+password]
ACTION: AUTHENTICATION_FAILED
APPLICATION: CAS
WHEN: Tue Aug 04 09:36:35 UTC 2015
CLIENT IP ADDRESS: 152.83.199.216
SERVER IP ADDRESS: nci-cas4.ala.org.au
=============================================================

>
2015-08-04 09:36:35,881 INFO [com.github.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
=============================================================
WHO: audit:unknown
WHAT: 1 errors, 0 successes
ACTION: TICKET_GRANTING_TICKET_NOT_CREATED
APPLICATION: CAS
WHEN: Tue Aug 04 09:36:35 UTC 2015
CLIENT IP ADDRESS: 152.83.199.216
SERVER IP ADDRESS: nci-cas4.ala.org.au
=============================================================

>
2015-08-04 09:36:35,881 ERROR [org.jasig.cas.integration.restlet.TicketResource] - <1 errors, 0 successes>
org.jasig.cas.authentication.AuthenticationException: 1 errors, 0 successes
        at org.jasig.cas.authentication.PolicyBasedAuthenticationManager.authenticateInternal(PolicyBasedAuthenticationManager.java:248)
        at org.jasig.cas.authentication.PolicyBasedAuthenticationManager.authenticate(PolicyBasedAuthenticationManager.java:143)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
...
```

**Comment by mmoayyed** [comment]
Yes, for 4.0.x the module is not deprecated. Only 4.1 which is consistent with our release strategy at which time the docs will reflect that. We have do have some workarounds documented on this issue; If you find a better alternative with restlet, please let us know. Otherwise, 4.1 it is.

**Comment by mbohun** [comment]
well, this is what i did for [ala-cas-2.0.1](https://github.com/AtlasOfLivingAustralia/ala-cas-2.0) (based on jasig cas-4.0.3) to work around this problem:

1. excluded restlet from the servlet filter in cas `web.xml`:

```xml
  <filter-mapping>
      <filter-name>requestParameterSecurityFilter</filter-name>
      <!-- list ALL URL patterns here, except restlet -->
      <url-pattern>/authorizationFailure.html</url-pattern>
      <url-pattern>/CentralAuthenticationService</url-pattern>
      <url-pattern>/login</url-pattern>
      <url-pattern>/logout</url-pattern>
      <url-pattern>/p3/proxyValidate</url-pattern>
      <url-pattern>/p3/serviceValidate</url-pattern>
      <url-pattern>/proxy</url-pattern>
      <url-pattern>/proxyValidate</url-pattern>
      <url-pattern>/serviceValidate</url-pattern>
      <url-pattern>/statistics</url-pattern>
      <url-pattern>/status</url-pattern>
      <url-pattern>/validate</url-pattern>
  </filter-mapping>
```

2. added a simple apache2 `<Location>` filter to our apache2 configuration that allows access to restlet only from a specific/configured IP address (of course this is not an universal workaround, we are lucky that we do not expose CAS REST interface to the outside world, only to one host):

```
<Location /cas/v1 >
   Order deny,allow
   Deny from all
   Allow from 11.22.33.44
</Location>
```

**Comment by mmoayyed** [comment]
Great! Could I ask you to submit a pull request? I will then update the docs to make this solution known.

**Comment by kayalvizhiameen** [comment]
Hi,
I was able to fix the issue by overriding the method 'obtainCredentials()' of 'TicketResource' class. It worked like a charm

**Comment by creekwise** [comment]
I have implemented kayalvizhiameen's solution and it works fine but only when the content type is text/* and not application/*.  I debugged CAS and the login credentials are lost unless sent in plain text, which makes me nervous to send them that way ('nervous' being an understatement). The authentication goes fine when sent in text. Can you help me solve this problem ?  Could it be that the service method (wherever it is) is annotated to accept text only and can that be overridden in the overlay ? Also, is there any way (without overriding) to get the service to return XML (or JSON) vs HTML ?

Here is my post on [stackoverflow](http://stackoverflow.com/questions/40558512/cas-rest-authentication-api-accepts-text-but-not-application-content-type).

**Comment by mmoayyed** [comment]
What problem are we solving exactly?

**Comment by dima767** [comment]
Let me add my 2c. The implementation of the REST module has been completely re-written in CAS 4.2.x with  native Spring MVC and does not present any of the above mentioned problems. I'd suggest upgrading.

The `4.0.x` branch will most likely be un-touched at this point.

**Comment by creekwise** [comment]
mmoayyed  --  the problem that I cannot send the message as 'application/x-www-form-urlencoded' content type but 'text/html' and that the response is in HTML and not XML/JSON

**Comment by dima767** [comment]
@creekwise See my comment above

**Comment by creekwise** [comment]
I can try that.  I hope that my implementation overlay will be forward compatible

**Comment by creekwise** [comment]
Also, can you recommend a stable X in 4.2.X ?

**Comment by dima767** [comment]
@creekwise Please do and report any issues you find for that version as `4.2.x` is the currently maintained version of CAS behind `5.0.0`

**Comment by dima767** [comment]
The latest stable release in the `4.2.x` series is `4.2.7`

**Comment by creekwise** [comment]
I don't seem to be able to find org.jasig.cas:cas-server-integration-restlet:jar:4.2.7 or 4.2.6.  is the restlet version the same as CAS version ?

**Comment by dima767** [comment]
`4.2` does not use restlet anymore. Use this reference doc: https://apereo.github.io/cas/4.2.x/protocol/REST-Protocol.html

**Comment by creekwise** [comment]
I was able to build OK but when I deployed, I got the following error:

```
2016-11-14 14:38:48,467 ERROR [org.springframework.web.context.ContextLoader] - <Context initialization failed

org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: The classes f
rom the spring-security-web jar (or one of its dependencies) are not available. You need these to use <http>
Offending resource: ServletContext resource [/WEB-INF/spring-configuration/securityContext.xml]; nested except
ion is java.lang.ClassNotFoundException: org.springframework.security.web.FilterChainProxy
        at org.springframework.beans.factory.parsing.FailFastProblemReporter.fatal(FailFastProblemReporter.jav
a:60)
        at org.springframework.beans.factory.parsing.ReaderContext.fatal(ReaderContext.java:68)
        at org.springframework.beans.factory.parsing.ReaderContext.fatal(ReaderContext.java:59)
```

I also added dependency

```
    <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-config</artifactId>
        <version>4.0.0.RELEASE</version>
    </dependency>
```

**Comment by creekwise** [comment]
In a nutshell, when I tried using 4.2.6 in my overlay, there was a series of class pathing incompatibilities in my overlay. While I am sure they can be fixed (which may require more than my familiarity with CAS), it is safe to say that my existing overlay (based on version CAS v 4.1.4) is **not forward compatible**.
